server:
  port: 8084
  address: 127.0.0.1
spring:
  main:
    allow-bean-definition-overriding: on
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leadermailbox?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: on
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: on
      # 监控配置
      stat-view-servlet:
        enabled: on
        reset-enable: false
        deny:
        allow:
        url-pattern: /druid/*
        login-username: admin
        login-password: 123456
      web-stat-filter:
        enabled: on
        url-pattern: /*
        exclusions: "*,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        ## stat是统计，wall是SQL防火墙，防SQL注入的，log4j是用来输出统计数据的
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # Spring监控配置，对spring内部接口调用的监控 说明请参考Druid Github Wiki，配置_Druid和Spring关联监控配置
      aop-patterns: com.skybrian.leadermailbox.service.*.*
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: on
    schema:
      - classpath:sql/department.sql
      - classpath:sql/employee.sql
    # 必须要指定always 方可生效
    initialization-mode: embedded
  flyway:
    enabled: off
    check-location: off
  application:
    name: leadermailbox_main
  boot:
    admin:
      client:
        url: http://127.0.0.1:8085
  #  security:
  #    user:
  #      name: admin
  #      password: 123456
  #      roles: ADMIN
  #  mail:
  #    host: smtp.qq.com
  #    username: 506997994@qq.com
  #    password: Vivi@1005
  #    properties:
  #      mail:
  #        smtp:
  #          auth: true
  #          starttls:
  #            enable: true
  #            required: true
  #    test-connection: true
  elasticsearch:
    rest:
      uris: http://192.168.175.128:9200
    jest:
      multi-threaded: on
  jpa:
    show-sql: on
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: on
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database: mysql
    # 必须指定数据库方言，如果是5，则指定所用引擎InnoDB，不然默认是MyISAM；如果是8，则不需要指定引擎，默认就是InnoDB
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: on
    properties:
      hibernate:
        format_sql: on
  quartz:
    auto-startup: off
  redis:
    host: 192.168.175.128
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-returns: on
    listener:
      simple:
#        发送消息后直接确认消息:none
#        根据消息消费的情况，智能判定消息的确认情况:auto
#        手动确认消息的情况:manual
        acknowledge-mode: manual
#    template:
#      default-receive-queue: [rabbitmq-queue]
#    properties:
#      hibernate:
#        dialect:
#          storage_engine: innodb
management:
  endpoints:
    web:
      exposure:
        include: '*'
swagger:
  enabled: on
  title: 领导信箱RESTFUL API文档
  description: spring boot2-swagger2
  version: 2.9.2
  license: Apache License, Version 2.0
  license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    name: jovi
    url: https://github.com/jovi521
    email: 506997994@qq.com
  base-package: com.skybrian.leadermailbox
  base-path: /**
  exclude-path: /error
  #  docket:
  #    docket1:
  #      title: 文档分组1
  #    docket2:
  #      title: 文档分组2
  ui-config:
    show-request-headers: on
mybatis-plus:
  config-location:
  mapper-locations: [classpath:mybatis/mapper/*.xml]
  configuration:
    map-underscore-to-camel-case: on
    #    控制台打印mybatis sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql
#  returnPageInfo: check
sharding:
  jdbc:
    datasource:
      names: leadermailbox
      leadermailbox:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/leadermailbox?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
    config:
      props:
        sql:
          show: true
#      sharding:
#        default-database-strategy:
#          inline:
#            sharding-column: id

